#pragma once
#define _XOPEN_SOURCE
#define _BSD_SOURCE
#define MODULE_COMPILEFLAGS "_ISYSTEM_HOST_MKFS_MSDOSFS_INCLUDE"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_HOST_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "THIRD_PARTY_UAPP_MKFS_MSDOSFS_MKFS_MSDOS_C_THIRD_PARTY_UAPP_MKFS_MSDOSFS_MKFS_MSDOS_H_THIRD_PARTY_UAPP_MKFS_MSDOSFS_NEWFS_MSDOS_C"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "HOSTAPP"

