#pragma once
#define USER_COMPILEFLAGS "_INCLUDE___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H__FPIC__D_ALL_SOURCE 1__FSANITIZE SAFE_STACK__FSTACK_PROTECTOR_STRONG"
#define USER_CFLAGS ""
#define USER_CPPFLAGS ""
#define USER_ASMFLAGS ""
#define USER_LDFLAGS "_Z_COMBRELOC__Z_RELRO__Z_NOW__Z_TEXT___HASH_STYLE GNU___EH_FRAME_HDR"

