#pragma once
#define USE_LIBCRYPTO 1
#define MODULE_COMPILEFLAGS "_ISYSTEM_HOST_MERKLEROOT_INCLUDE__ISYSTEM_ULIB_DIGEST_INCLUDE__ISYSTEM_ULIB_MXALLOC_INCLUDE__ISYSTEM_ULIB_MXCPP_INCLUDE__ISYSTEM_ULIB_MXTL_INCLUDE"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_HOST_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "SYSTEM_HOST_MERKLEROOT_MERKLEROOT_CPP_SYSTEM_ULIB_DIGEST_DIGEST_CPP_SYSTEM_ULIB_DIGEST_MERKLE_TREE_CPP_SYSTEM_ULIB_MXALLOC_ALLOC_CHECKER_CPP"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "HOSTAPP"

