#pragma once
#define MODULE_COMPILEFLAGS ""
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_KERNEL_H"
#define MODULE_DEPS "KERNEL_LIB_FIXED_POINT"
#define MODULE_SRCS "KERNEL_DEV_TIMER_ARM_GENERIC_ARM_GENERIC_TIMER_C"
#define MODULE_HEADER_DEPS "KERNEL_LIB_FIXED_POINT"
#define MODULE_TYPE ""

