#pragma once
#define MODULE_COMPILEFLAGS "_ISYSTEM_HOST_MDI_INCLUDE"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_HOST_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "SYSTEM_HOST_MDI_MDIGEN_CPP_SYSTEM_HOST_MDI_NODE_CPP_SYSTEM_HOST_MDI_PARSER_CPP_SYSTEM_HOST_MDI_TOKENS_CPP"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "HOSTAPP"

