// This file is generated by scripts/gen-vdso-valid-sysret.sh.  DO NOT EDIT.

#include <stdint.h>
#include "vdso-code.h"

struct VDso::ValidSyscallPC {

    static bool futex_wake(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_futex_wake_VIA_mx_futex_wake_handle_close_thread_exit - VDSO_CODE_START:
            return true;
        case VDSO_CODE_SYSRET_mx_futex_wake_VIA_mx_futex_wake - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool handle_close(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_handle_close_VIA_mx_futex_wake_handle_close_thread_exit - VDSO_CODE_START:
            return true;
        case VDSO_CODE_SYSRET_mx_handle_close_VIA_mx_vmar_unmap_handle_close_thread_exit - VDSO_CODE_START:
            return true;
        case VDSO_CODE_SYSRET_mx_handle_close_VIA_mx_handle_close - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool thread_exit(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_thread_exit_VIA_mx_futex_wake_handle_close_thread_exit - VDSO_CODE_START:
            return true;
        case VDSO_CODE_SYSRET_mx_thread_exit_VIA_mx_vmar_unmap_handle_close_thread_exit - VDSO_CODE_START:
            return true;
        case VDSO_CODE_SYSRET_mx_thread_exit_VIA_mx_thread_exit - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmar_unmap(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmar_unmap_VIA_mx_vmar_unmap_handle_close_thread_exit - VDSO_CODE_START:
            return true;
        case VDSO_CODE_SYSRET_mx_vmar_unmap_VIA_mx_vmar_unmap - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool time_get(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_time_get_VIA_mx_time_get - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool nanosleep(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_nanosleep_VIA_mx_nanosleep - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool handle_duplicate(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_handle_duplicate_VIA_mx_handle_duplicate - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool handle_replace(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_handle_replace_VIA_mx_handle_replace - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_wait_one(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_wait_one_VIA_mx_object_wait_one - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_wait_many(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_wait_many_VIA_mx_object_wait_many - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_wait_async(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_wait_async_VIA_mx_object_wait_async - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_signal(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_signal_VIA_mx_object_signal - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_signal_peer(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_signal_peer_VIA_mx_object_signal_peer - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_get_property(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_get_property_VIA_mx_object_get_property - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_set_property(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_set_property_VIA_mx_object_set_property - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_set_cookie(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_set_cookie_VIA_mx_object_set_cookie - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_get_cookie(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_get_cookie_VIA_mx_object_get_cookie - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_get_info(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_get_info_VIA_mx_object_get_info - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool object_get_child(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_object_get_child_VIA_mx_object_get_child - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool channel_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_channel_create_VIA_mx_channel_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool channel_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_channel_read_VIA_mx_channel_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool channel_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_channel_write_VIA_mx_channel_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool channel_call_noretry(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_channel_call_noretry_VIA_mx_channel_call_noretry - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool channel_call_finish(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_channel_call_finish_VIA_mx_channel_call_finish - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool socket_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_socket_create_VIA_mx_socket_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool socket_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_socket_write_VIA_mx_socket_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool socket_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_socket_read_VIA_mx_socket_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool thread_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_thread_create_VIA_mx_thread_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool thread_start(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_thread_start_VIA_mx_thread_start - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool thread_read_state(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_thread_read_state_VIA_mx_thread_read_state - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool thread_write_state(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_thread_write_state_VIA_mx_thread_write_state - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool process_exit(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_process_exit_VIA_mx_process_exit - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool process_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_process_create_VIA_mx_process_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool process_start(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_process_start_VIA_mx_process_start - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool process_read_memory(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_process_read_memory_VIA_mx_process_read_memory - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool process_write_memory(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_process_write_memory_VIA_mx_process_write_memory - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool job_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_job_create_VIA_mx_job_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool job_set_policy(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_job_set_policy_VIA_mx_job_set_policy - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool task_bind_exception_port(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_task_bind_exception_port_VIA_mx_task_bind_exception_port - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool task_suspend(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_task_suspend_VIA_mx_task_suspend - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool task_resume(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_task_resume_VIA_mx_task_resume - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool task_kill(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_task_kill_VIA_mx_task_kill - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool event_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_event_create_VIA_mx_event_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool eventpair_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_eventpair_create_VIA_mx_eventpair_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool futex_wait(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_futex_wait_VIA_mx_futex_wait - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool futex_requeue(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_futex_requeue_VIA_mx_futex_requeue - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool waitset_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_waitset_create_VIA_mx_waitset_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool waitset_add(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_waitset_add_VIA_mx_waitset_add - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool waitset_remove(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_waitset_remove_VIA_mx_waitset_remove - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool waitset_wait(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_waitset_wait_VIA_mx_waitset_wait - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool port_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_port_create_VIA_mx_port_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool port_queue(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_port_queue_VIA_mx_port_queue - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool port_wait(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_port_wait_VIA_mx_port_wait - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool port_cancel(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_port_cancel_VIA_mx_port_cancel - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool timer_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_timer_create_VIA_mx_timer_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool timer_start(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_timer_start_VIA_mx_timer_start - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool timer_cancel(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_timer_cancel_VIA_mx_timer_cancel - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_create_VIA_mx_vmo_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_read_VIA_mx_vmo_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_write_VIA_mx_vmo_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_get_size(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_get_size_VIA_mx_vmo_get_size - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_set_size(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_set_size_VIA_mx_vmo_set_size - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_op_range(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_op_range_VIA_mx_vmo_op_range - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_clone(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_clone_VIA_mx_vmo_clone - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_set_cache_policy(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_set_cache_policy_VIA_mx_vmo_set_cache_policy - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmar_allocate(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmar_allocate_VIA_mx_vmar_allocate - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmar_destroy(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmar_destroy_VIA_mx_vmar_destroy - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmar_map(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmar_map_VIA_mx_vmar_map - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmar_protect(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmar_protect_VIA_mx_vmar_protect - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool cprng_draw(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_cprng_draw_VIA_mx_cprng_draw - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool cprng_add_entropy(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_cprng_add_entropy_VIA_mx_cprng_add_entropy - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool fifo_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_fifo_create_VIA_mx_fifo_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool fifo_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_fifo_read_VIA_mx_fifo_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool fifo_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_fifo_write_VIA_mx_fifo_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool log_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_log_create_VIA_mx_log_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool log_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_log_write_VIA_mx_log_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool log_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_log_read_VIA_mx_log_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool ktrace_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_ktrace_read_VIA_mx_ktrace_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool ktrace_control(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_ktrace_control_VIA_mx_ktrace_control - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool ktrace_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_ktrace_write_VIA_mx_ktrace_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool mtrace_control(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_mtrace_control_VIA_mx_mtrace_control - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool debug_transfer_handle(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_debug_transfer_handle_VIA_mx_debug_transfer_handle - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool debug_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_debug_read_VIA_mx_debug_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool debug_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_debug_write_VIA_mx_debug_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool debug_send_command(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_debug_send_command_VIA_mx_debug_send_command - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool interrupt_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_interrupt_create_VIA_mx_interrupt_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool interrupt_complete(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_interrupt_complete_VIA_mx_interrupt_complete - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool interrupt_wait(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_interrupt_wait_VIA_mx_interrupt_wait - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool interrupt_signal(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_interrupt_signal_VIA_mx_interrupt_signal - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool mmap_device_io(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_mmap_device_io_VIA_mx_mmap_device_io - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool mmap_device_memory(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_mmap_device_memory_VIA_mx_mmap_device_memory - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool io_mapping_get_info(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_io_mapping_get_info_VIA_mx_io_mapping_get_info - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool vmo_create_contiguous(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_vmo_create_contiguous_VIA_mx_vmo_create_contiguous - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool bootloader_fb_get_info(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_bootloader_fb_get_info_VIA_mx_bootloader_fb_get_info - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool set_framebuffer(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_set_framebuffer_VIA_mx_set_framebuffer - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool set_framebuffer_vmo(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_set_framebuffer_vmo_VIA_mx_set_framebuffer_vmo - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool clock_adjust(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_clock_adjust_VIA_mx_clock_adjust - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_get_nth_device(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_get_nth_device_VIA_mx_pci_get_nth_device - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_claim_device(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_claim_device_VIA_mx_pci_claim_device - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_enable_bus_master(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_enable_bus_master_VIA_mx_pci_enable_bus_master - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_enable_pio(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_enable_pio_VIA_mx_pci_enable_pio - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_reset_device(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_reset_device_VIA_mx_pci_reset_device - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_get_bar(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_get_bar_VIA_mx_pci_get_bar - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_get_config(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_get_config_VIA_mx_pci_get_config - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_io_write(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_io_write_VIA_mx_pci_io_write - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_io_read(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_io_read_VIA_mx_pci_io_read - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_map_interrupt(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_map_interrupt_VIA_mx_pci_map_interrupt - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_query_irq_mode_caps(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_query_irq_mode_caps_VIA_mx_pci_query_irq_mode_caps - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_set_irq_mode(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_set_irq_mode_VIA_mx_pci_set_irq_mode - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_init(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_init_VIA_mx_pci_init - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool pci_add_subtract_io_range(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_pci_add_subtract_io_range_VIA_mx_pci_add_subtract_io_range - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool acpi_uefi_rsdp(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_acpi_uefi_rsdp_VIA_mx_acpi_uefi_rsdp - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool acpi_cache_flush(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_acpi_cache_flush_VIA_mx_acpi_cache_flush - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool resource_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_resource_create_VIA_mx_resource_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool resource_destroy(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_resource_destroy_VIA_mx_resource_destroy - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool resource_get_handle(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_resource_get_handle_VIA_mx_resource_get_handle - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool resource_do_action(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_resource_do_action_VIA_mx_resource_do_action - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool resource_connect(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_resource_connect_VIA_mx_resource_connect - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool resource_accept(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_resource_accept_VIA_mx_resource_accept - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool hypervisor_create(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_hypervisor_create_VIA_mx_hypervisor_create - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool hypervisor_op(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_hypervisor_op_VIA_mx_hypervisor_op - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool system_mexec(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_system_mexec_VIA_mx_system_mexec - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_0(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_0_VIA_mx_syscall_test_0 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_1(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_1_VIA_mx_syscall_test_1 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_2(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_2_VIA_mx_syscall_test_2 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_3(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_3_VIA_mx_syscall_test_3 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_4(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_4_VIA_mx_syscall_test_4 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_5(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_5_VIA_mx_syscall_test_5 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_6(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_6_VIA_mx_syscall_test_6 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_7(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_7_VIA_mx_syscall_test_7 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_8(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_8_VIA_mx_syscall_test_8 - VDSO_CODE_START:
            return true;
        }
        return false;
    }

    static bool syscall_test_wrapper(uintptr_t offset) {
        switch (offset) {
        case VDSO_CODE_SYSRET_mx_syscall_test_wrapper_VIA_mx_syscall_test_wrapper - VDSO_CODE_START:
            return true;
        }
        return false;
    }

};
