#pragma once
#define MODULE_COMPILEFLAGS ""
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_KERNEL_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "SYSTEM_ULIB_MXALLOC_ALLOC_CHECKER_CPP"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE ""

