#pragma once
#define MODULE_COMPILEFLAGS "_ISYSTEM_ULIB_TFTP_INCLUDE__STD C11"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_HOST_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "SYSTEM_ULIB_TFTP_TFTP_EXAMPLE_C_SYSTEM_ULIB_TFTP_TFTP_C"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "HOSTAPP"

