#pragma once
#define MODULE_COMPILEFLAGS ""
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_KERNEL_H"
#define MODULE_DEPS "KERNEL_APP_KERNEL_DEV_KERNEL_KERNEL_KERNEL_PLATFORM_KERNEL_TARGET"
#define MODULE_SRCS "KERNEL_TOP_INIT_C_KERNEL_TOP_MAIN_C"
#define MODULE_HEADER_DEPS "KERNEL_APP_KERNEL_DEV_KERNEL_KERNEL_KERNEL_PLATFORM_KERNEL_TARGET"
#define MODULE_TYPE ""

