#pragma once
#define MODULE_COMPILEFLAGS "_ISYSTEM_HOST_FIDL_INCLUDE__O0__G"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_HOST_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "SYSTEM_HOST_FIDL_IDENTIFIER_TABLE_CPP_SYSTEM_HOST_FIDL_LEXER_CPP_SYSTEM_HOST_FIDL_MAIN_CPP_SYSTEM_HOST_FIDL_PARSER_CPP_SYSTEM_HOST_FIDL_SOURCE_MANAGER_CPP"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "HOSTAPP"

