#pragma once
#define MODULE_COMPILEFLAGS "_I__BUILD_MAGENTA_QEMU_ARM64_CLANG_KERNEL_LIB_USERBOOT"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_KERNEL_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_KERNEL_LIB_USERBOOT_USERBOOT_CODE_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_SYSTEM_CORE_USERBOOT_LIBUSERBOOT_SO_STRIP"
#define MODULE_DEPS "KERNEL_LIB_VDSO"
#define MODULE_SRCS "KERNEL_LIB_USERBOOT_USERBOOT_IMAGE_S_KERNEL_LIB_USERBOOT_USERBOOT_CPP"
#define MODULE_HEADER_DEPS "KERNEL_LIB_VDSO"
#define MODULE_TYPE ""

