#pragma once
#define MODULE_COMPILEFLAGS "_ISYSTEM_HOST_MKBOOTFS_INCLUDE"
#define MODULE_CFLAGS "_ITHIRD_PARTY_ULIB_LZ4_INCLUDE_LZ4"
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_HOST_H___BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_USER_H"
#define MODULE_DEPS ""
#define MODULE_SRCS "SYSTEM_HOST_MKBOOTFS_MKBOOTFS_C_THIRD_PARTY_ULIB_LZ4_LZ4_C_THIRD_PARTY_ULIB_LZ4_LZ4FRAME_C_THIRD_PARTY_ULIB_LZ4_LZ4HC_C_THIRD_PARTY_ULIB_LZ4_XXHASH_C"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "HOSTAPP"

