#pragma once
#define MODULE_COMPILEFLAGS ""
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "__BUILD_MAGENTA_QEMU_ARM64_CLANG_CONFIG_KERNEL_H"
#define MODULE_DEPS "KERNEL_LIB_HEAP_CMPCTMALLOC_KERNEL_LIB_MXKASAN"
#define MODULE_SRCS "KERNEL_LIB_HEAP_HEAP_WRAPPER_CPP"
#define MODULE_HEADER_DEPS "KERNEL_LIB_HEAP_CMPCTMALLOC_KERNEL_LIB_MXKASAN"
#define MODULE_TYPE ""

